### ISSUE TITLE
Problem about chatgpt install

### ISSUE THREAD

**Issue by a962097364** [dilmerv/UnityChatGPT#2]
Hello！Thanks for your great work！
I am trying to install chatgpt-wrapper and login OpenAI, but when I use **chatgpt install** commend, this problem comes out:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)
                ~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chatgpt\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT', 'console_scripts', 'chatgpt')())
  File "C:\ProgramData\Anaconda3\envs\chatgpt\Scripts\chatgpt-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\3d\unitychatgpt-master\service\chatgpt-wrapper\lwe\__init__.py", line 1, in <module>
    from lwe.backends.api.backend import ApiBackend
  File "d:\3d\unitychatgpt-master\service\chatgpt-wrapper\lwe\backends\api\backend.py", line 9, in <module>
    from lwe.core.provider_manager import ProviderManager
  File "d:\3d\unitychatgpt-master\service\chatgpt-wrapper\lwe\core\provider_manager.py", line 4, in <module>
    from lwe.core.plugin_manager import PluginManager
  File "d:\3d\unitychatgpt-master\service\chatgpt-wrapper\lwe\core\plugin_manager.py", line 3, in <module>
    import pkg_resources
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3327, in <module>
    def _initialize_master_working_set():
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 832, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 2821, in requires
    dm = self._dep_map
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3120, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\__init__.py", line 3173, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)

I use Anaconda create an environment, and this is my pip list:
 ai21                    1.1.4
aiohttp                 3.8.4
aiosignal               1.3.1
alembic                 1.11.1
ansible                 8.0.0
ansible-core            2.15.0
argcomplete             1.10.3
async-timeout           4.0.2
attrs                   23.1.0
backoff                 2.2.1
beautifulsoup4          4.8.2
blinker                 1.6.2
certifi                 2023.5.7
cffi                    1.15.1
chardet                 3.0.4
charset-normalizer      3.1.0
chatGPT                 0.12.2      d:\3d\unitychatgpt-master\service\chatgpt-wrapper
click                   8.1.3
cohere                  4.11.2
colorama                0.4.6
compressed-rtf          1.0.6
cryptography            41.0.1
dataclasses-json        0.5.8
dnspython               2.3.0
docx2txt                0.8
ebcdic                  1.1.1
email-validator         2.0.0.post2
et-xmlfile              1.1.0
extract-msg             0.28.7
filelock                3.12.2
Flask                   2.3.2
frozenlist              1.3.3
fsspec                  2023.6.0
greenlet                2.0.2
huggingface-hub         0.15.1
idna                    3.4
IMAPClient              2.1.0
importlib-metadata      6.6.0
importlib-resources     5.0.7
itsdangerous            2.1.2
Jinja2                  3.1.2
langchain               0.0.199
langchainplus-sdk       0.0.10
lxml                    4.9.2
Mako                    1.2.4
markdown-it-py          3.0.0
MarkupSafe              2.1.3
marshmallow             3.19.0
marshmallow-enum        1.5.1
mdurl                   0.1.2
multidict               6.0.4
mypy-extensions         1.0.0
names                   0.3.0
numexpr                 2.8.4
numpy                   1.24.3
olefile                 0.46
openai                  0.27.8
openapi-schema-pydantic 1.2.4
openpyxl                3.1.2
packaging               23.1
pdfminer.six            20191110
Pillow                  9.5.0
pip                     23.1.2
playwright              1.35.0
prompt-toolkit          3.0.38
pycparser               2.21
pycryptodome            3.18.0
pydantic                1.10.9
pydantic-computed       0.2.2
pyee                    9.0.4
Pygments                2.15.1
pyperclip               1.8.2
pyreadline3             3.4.1
python-frontmatter      1.0.0
python-pptx             0.6.21
PyYAML                  6.0
regex                   2023.6.3
requests                2.31.0
resolvelib              1.0.1
rich                    13.4.2
setuptools              67.8.0
six                     1.12.0
sortedcontainers        2.4.0
soupsieve               2.4.1
SpeechRecognition       3.8.1
SQLAlchemy              2.0.0
tenacity                8.2.2
textract                1.6.5
tiktoken                0.4.0
tqdm                    4.65.0
typing_extensions       4.6.3
typing-inspect          0.9.0
tzdata                  2023.3
tzlocal                 5.0.1
urllib3                 2.0.3
wcwidth                 0.2.6
Werkzeug                2.3.6
wheel                   0.38.4
xlrd                    1.2.0
XlsxWriter              3.1.2
yarl                    1.9.2
zipp                    3.15.0

**Comment by a962097364** [comment]
I install chatgpt-wrapper by using :
git clone https://github.com/mmabrouk/chatgpt-wrapper.git
cd chatgpt-wrapper
pip install -e .

and it is work.
